export const FETCH_PHONES_START = "FETCH_PHONES_START";
export const FETCH_PHONES_SUCCESS = "FETCH_PHONES_SUCCESS";
export const FETCH_PHONES_FAILED = "FETCH_PHONES_FAILED";
export const LOAD_MORE_PHONE_START = "LOAD_MORE_PHONE_START";
export const LOAD_MORE_PHONE_SUCCESS = "LOAD_MORE_PHONE_SUCCESS";
export const LOAD_MORE_PHONES_FAILED = "LOAD_MORE_PHONES_FAILED";