export const FETCH_PHONES_START = "FETCH_PHONES_START";
export const FETCH_PHONES_SUCCESS = "FETCH_PHONES_SUCCESS";
export const FETCH_PHONES_FAILED = "FETCH_PHONES_FAILED";

export const LOAD_MORE_PHONE_START = "LOAD_MORE_PHONE_START";
export const LOAD_MORE_PHONE_SUCCESS = "LOAD_MORE_PHONE_SUCCESS";
export const LOAD_MORE_PHONES_FAILED = "LOAD_MORE_PHONES_FAILED";

export const FETCH_PHONE_BY_ID_START = "FETCH_PHONE_BY_ID_START";
export const FETCH_PHONE_BY_ID_SUCCESS = "FETCH_PHONE_BY_ID_SUCCESS";
export const FETCH_PHONE_BY_ID_FAILED = "FETCH_PHONE_BY_ID_FAILED";

export const ADD_PHONE_TO_BASKET = "ADD_PHONE_TO_BASKET";

export const SEARCH_PHONE = "SEARCH_PHONE";

export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORIES_FAILED";